-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema infs3_prj09
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema infs3_prj09
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `infs3_prj09` DEFAULT CHARACTER SET latin1 ;
USE `infs3_prj09` ;

-- -----------------------------------------------------
-- Table `infs3_prj09`.`ENTREPRISE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3_prj09`.`ENTREPRISE` ;

CREATE TABLE IF NOT EXISTS `infs3_prj09`.`ENTREPRISE` (
  `ID_ENTREPRISE` INT(10) NOT NULL AUTO_INCREMENT,
  `LIB_ENTREPRISE` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ENTREPRISE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infs3_prj09`.`ADRESSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3_prj09`.`ADRESSE` ;

CREATE TABLE IF NOT EXISTS `infs3_prj09`.`ADRESSE` (
  `ID_ADRESSE` INT(10) NOT NULL AUTO_INCREMENT,
  `ID_ENTREPRISE` INT(10) NULL DEFAULT NULL,
  `RUE` VARCHAR(100) NULL DEFAULT NULL,
  `CODE_POSTAL` VARCHAR(5) NULL DEFAULT NULL,
  `VILLE` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ADRESSE`),
  INDEX `FK_ADRESSE_AVOIR_ADR_ENTREPRI` (`ID_ENTREPRISE` ASC) VISIBLE,
  CONSTRAINT `FK_ADRESSE_AVOIR_ADR_ENTREPRI`
    FOREIGN KEY (`ID_ENTREPRISE`)
    REFERENCES `infs3_prj09`.`ENTREPRISE` (`ID_ENTREPRISE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infs3_prj09`.`UTILISATEUR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3_prj09`.`UTILISATEUR` ;

CREATE TABLE IF NOT EXISTS `infs3_prj09`.`UTILISATEUR` (
  `ID_PERS` INT(10) NOT NULL AUTO_INCREMENT,
  `ID_ADRESSE` INT(10) NULL DEFAULT NULL,
  `NOM` VARCHAR(25) NOT NULL,
  `PRENOM` VARCHAR(25) NULL DEFAULT NULL,
  `GENRE` VARCHAR(1) NULL DEFAULT NULL,
  `DATENAIS` DATE NULL DEFAULT NULL,
  `MAIL` VARCHAR(100) NULL DEFAULT NULL,
  `LOGIN` VARCHAR(25) NOT NULL,
  `SHA_MDP` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ID_PERS`),
  INDEX `FK_UTILISAT_AVOIR_ADR_ADRESSE` (`ID_ADRESSE` ASC) VISIBLE,
  CONSTRAINT `FK_UTILISAT_AVOIR_ADR_ADRESSE`
    FOREIGN KEY (`ID_ADRESSE`)
    REFERENCES `infs3_prj09`.`ADRESSE` (`ID_ADRESSE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infs3_prj09`.`PROFESSEUR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3_prj09`.`PROFESSEUR` ;

CREATE TABLE IF NOT EXISTS `infs3_prj09`.`PROFESSEUR` (
  `ID_PERS` INT(10) NOT NULL,
  `N_PROF` INT(11) NOT NULL,
  PRIMARY KEY (`ID_PERS`),
  CONSTRAINT `FK_PROFESSE_H_TILISAT_UTILISAT`
    FOREIGN KEY (`ID_PERS`)
    REFERENCES `infs3_prj09`.`UTILISATEUR` (`ID_PERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infs3_prj09`.`PROJET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3_prj09`.`PROJET` ;

CREATE TABLE IF NOT EXISTS `infs3_prj09`.`PROJET` (
  `ID_PROJET` INT(5) NOT NULL AUTO_INCREMENT,
  `ID_PERS` INT(10) NULL DEFAULT NULL,
  `LIB_PROJET` VARCHAR(100) NOT NULL,
  `DATE_DEB_PROJET` DATE NULL DEFAULT NULL,
  `DATE_FIN_PROJET` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PROJET`),
  INDEX `FK_PROJET_PROPOSER__PROFESSE` (`ID_PERS` ASC) VISIBLE,
  CONSTRAINT `FK_PROJET_PROPOSER__PROFESSE`
    FOREIGN KEY (`ID_PERS`)
    REFERENCES `infs3_prj09`.`PROFESSEUR` (`ID_PERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infs3_prj09`.`RESPONSABLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3_prj09`.`RESPONSABLE` ;

CREATE TABLE IF NOT EXISTS `infs3_prj09`.`RESPONSABLE` (
  `ID_PERS` INT(10) NOT NULL,
  `ID_ENTREPRISE` INT(10) NULL DEFAULT NULL,
  `ID_STAGE` INT(5) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PERS`),
  INDEX `FK_RESPONSA_EMPLOYER_ENTREPRI` (`ID_ENTREPRISE` ASC) VISIBLE,
  INDEX `FK_RESPONSA_ENCADRER2_STAGE` (`ID_STAGE` ASC) VISIBLE,
  CONSTRAINT `FK_RESPONSA_EMPLOYER_ENTREPRI`
    FOREIGN KEY (`ID_ENTREPRISE`)
    REFERENCES `infs3_prj09`.`ENTREPRISE` (`ID_ENTREPRISE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RESPONSA_ENCADRER2_STAGE`
    FOREIGN KEY (`ID_STAGE`)
    REFERENCES `infs3_prj09`.`STAGE` (`ID_STAGE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RESPONSA_H_TILISAT_UTILISAT`
    FOREIGN KEY (`ID_PERS`)
    REFERENCES `infs3_prj09`.`UTILISATEUR` (`ID_PERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infs3_prj09`.`STAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3_prj09`.`STAGE` ;

CREATE TABLE IF NOT EXISTS `infs3_prj09`.`STAGE` (
  `ID_STAGE` INT(5) NOT NULL AUTO_INCREMENT,
  `ID_ENTREPRISE` INT(10) NULL DEFAULT NULL,
  `RESPONSABLE_ID_PERS` INT(10) NULL DEFAULT NULL,
  `LIB_STAGE` VARCHAR(100) NULL DEFAULT NULL,
  `DATE_DEB_STAGE` DATE NOT NULL,
  `DATE_FIN_STAGE` DATE NOT NULL,
  `PROFESSEUR_ID_PERS` INT(10) NULL,
  PRIMARY KEY (`ID_STAGE`),
  INDEX `FK_STAGE_ENCADRER_RESPONSA` (`RESPONSABLE_ID_PERS` ASC) VISIBLE,
  INDEX `FK_STAGE_PROPOSER__ENTREPRI` (`ID_ENTREPRISE` ASC) VISIBLE,
  INDEX `fk_STAGE_PROFESSEUR1_idx` (`PROFESSEUR_ID_PERS` ASC) VISIBLE,
  CONSTRAINT `FK_STAGE_ENCADRER_RESPONSA`
    FOREIGN KEY (`RESPONSABLE_ID_PERS`)
    REFERENCES `infs3_prj09`.`RESPONSABLE` (`ID_PERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_STAGE_PROPOSER__ENTREPRI`
    FOREIGN KEY (`ID_ENTREPRISE`)
    REFERENCES `infs3_prj09`.`ENTREPRISE` (`ID_ENTREPRISE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STAGE_PROFESSEUR1`
    FOREIGN KEY (`PROFESSEUR_ID_PERS`)
    REFERENCES `infs3_prj09`.`PROFESSEUR` (`ID_PERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infs3_prj09`.`PROPOSITION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3_prj09`.`PROPOSITION` ;

CREATE TABLE IF NOT EXISTS `infs3_prj09`.`PROPOSITION` (
  `ID_PROPOSITION` INT(10) NOT NULL AUTO_INCREMENT,
  `ID_STAGE` INT(5) NULL DEFAULT NULL,
  `ID_PROJET` INT(5) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PROPOSITION`),
  INDEX `FK_PROPOSITION_LIER_PROJET` (`ID_PROJET` ASC) VISIBLE,
  INDEX `FK_PROPOSITION_LIER_STAGE` (`ID_STAGE` ASC) VISIBLE,
  CONSTRAINT `FK_PROPOSITION_LIER_PROJET`
    FOREIGN KEY (`ID_PROJET`)
    REFERENCES `infs3_prj09`.`PROJET` (`ID_PROJET`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROPOSITION_LIER_STAGE`
    FOREIGN KEY (`ID_STAGE`)
    REFERENCES `infs3_prj09`.`STAGE` (`ID_STAGE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infs3_prj09`.`ETUDIANT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3_prj09`.`ETUDIANT` ;

CREATE TABLE IF NOT EXISTS `infs3_prj09`.`ETUDIANT` (
  `ID_PERS` INT(10) NOT NULL,
  `ID_PROJET` INT(5) NULL DEFAULT NULL,
  `ID_STAGE` INT(5) NULL DEFAULT NULL,
  `N_ETUD` INT(11) NOT NULL,
  PRIMARY KEY (`ID_PERS`),
  INDEX `FK_ETUDIANT_REALISER__PROJET` (`ID_PROJET` ASC) VISIBLE,
  INDEX `FK_ETUDIANT_REALISER__STAGE` (`ID_STAGE` ASC) VISIBLE,
  CONSTRAINT `FK_ETUDIANT_H_TILISAT_UTILISAT`
    FOREIGN KEY (`ID_PERS`)
    REFERENCES `infs3_prj09`.`UTILISATEUR` (`ID_PERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ETUDIANT_REALISER__PROJET`
    FOREIGN KEY (`ID_PROJET`)
    REFERENCES `infs3_prj09`.`PROJET` (`ID_PROJET`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ETUDIANT_REALISER__STAGE`
    FOREIGN KEY (`ID_STAGE`)
    REFERENCES `infs3_prj09`.`STAGE` (`ID_STAGE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infs3_prj09`.`CANDIDATER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3_prj09`.`CANDIDATER` ;

CREATE TABLE IF NOT EXISTS `infs3_prj09`.`CANDIDATER` (
  `ID_PERS` INT(10) NOT NULL,
  `ID_PROPOSITION` INT(10) NOT NULL,
  `DATE_CAND` DATE NULL DEFAULT NULL,
  `POURVUE` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PERS`, `ID_PROPOSITION`),
  INDEX `FK_PROPOSITION_CANDIDATER_PROPOSITION` (`ID_PROPOSITION` ASC) VISIBLE,
  CONSTRAINT `FK_PROPOSITION_CANDIDATER_PROPOSITION`
    FOREIGN KEY (`ID_PROPOSITION`)
    REFERENCES `infs3_prj09`.`PROPOSITION` (`ID_PROPOSITION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROPOSITION_CANDIDATER_ETUDIANT`
    FOREIGN KEY (`ID_PERS`)
    REFERENCES `infs3_prj09`.`ETUDIANT` (`ID_PERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infs3_prj09`.`MODULE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3_prj09`.`MODULE` ;

CREATE TABLE IF NOT EXISTS `infs3_prj09`.`MODULE` (
  `ID_MODULE` VARCHAR(5) NOT NULL,
  `LIB_MODULE` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_MODULE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infs3_prj09`.`ENSEIGNER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3_prj09`.`ENSEIGNER` ;

CREATE TABLE IF NOT EXISTS `infs3_prj09`.`ENSEIGNER` (
  `ID_MODULE` VARCHAR(5) NOT NULL,
  `ID_PERS` INT(10) NOT NULL,
  PRIMARY KEY (`ID_MODULE`, `ID_PERS`),
  INDEX `FK_ENSEIGNE_ENSEIGNER_PROFESSE` (`ID_PERS` ASC) VISIBLE,
  CONSTRAINT `FK_ENSEIGNE_ENSEIGNER_MODULE`
    FOREIGN KEY (`ID_MODULE`)
    REFERENCES `infs3_prj09`.`MODULE` (`ID_MODULE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ENSEIGNE_ENSEIGNER_PROFESSE`
    FOREIGN KEY (`ID_PERS`)
    REFERENCES `infs3_prj09`.`PROFESSEUR` (`ID_PERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infs3_prj09`.`INSCRIRE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3_prj09`.`INSCRIRE` ;

CREATE TABLE IF NOT EXISTS `infs3_prj09`.`INSCRIRE` (
  `ID_MODULE` VARCHAR(5) NOT NULL,
  `ID_PERS` INT(10) NOT NULL,
  `NOTE_CC` DECIMAL(4,0) NULL DEFAULT NULL,
  `NOTE_TP` DECIMAL(4,0) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_MODULE`, `ID_PERS`),
  INDEX `FK_INSCRIRE_INSCRIRE2_ETUDIANT` (`ID_PERS` ASC) VISIBLE,
  CONSTRAINT `FK_INSCRIRE_INSCRIRE2_ETUDIANT`
    FOREIGN KEY (`ID_PERS`)
    REFERENCES `infs3_prj09`.`ETUDIANT` (`ID_PERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_INSCRIRE_INSCRIRE_MODULE`
    FOREIGN KEY (`ID_MODULE`)
    REFERENCES `infs3_prj09`.`MODULE` (`ID_MODULE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `infs3_prj09`;

DELIMITER $$

USE `infs3_prj09`$$
DROP TRIGGER IF EXISTS `infs3_prj09`.`INSERT_PASS_TO_SHA` $$
USE `infs3_prj09`$$
CREATE
DEFINER=`infs3_prj09`@`%`
TRIGGER `infs3_prj09`.`INSERT_PASS_TO_SHA`
BEFORE INSERT ON `infs3_prj09`.`UTILISATEUR`
FOR EACH ROW
SET NEW.SHA_MDP = SHA2(NEW.SHA_MDP, 512)$$


USE `infs3_prj09`$$
DROP TRIGGER IF EXISTS `infs3_prj09`.`UPDATE_PASS_TO_SHA` $$
USE `infs3_prj09`$$
CREATE
DEFINER=`infs3_prj09`@`%`
TRIGGER `infs3_prj09`.`UPDATE_PASS_TO_SHA`
BEFORE UPDATE ON `infs3_prj09`.`UTILISATEUR`
FOR EACH ROW
SET NEW.SHA_MDP = SHA2(NEW.SHA_MDP, 512)$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
